language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "damqa7lOxwAv0jkf5ZP9XBIFKTeYTI84H9UOPpuhQSVUqWZ3UEc9Fft8XsKD5bvqBvXCY1Eo8gwVxgRqndmG+fEIZ
y/7AyG3ttyiv0gPgxvfA+CgFXeTSvG1v1O6yV3hKMWzuK+UOEPGF9+8tPDYuLUiVpmt6DPmeVI82deNCUdwSHfrgMq6VDnS1NaEP
boCSi75sZhvDvvI3GPt7HOJ0MlXmh++qcIQ7CJLRDteBoKA9UfTF3uJNFC1UKIWH7wzl//1YI/PmWi2Yu0oBWd5bmB7y4PHdebb9
wLlZsxb70fGppw0W5r4wwXAGrQ4471hnuFt/0gYtOc2x71UJ23t7jwnx60uHFW66NJBrPUlOUJTK7tgzD0xv7gS458ETmNvkib2Q
3Fr5tl+37rv0gLhEd2n+6+XE2eKCquSZSToTycIg5+HzAlj6DTDut/bQT3Ehjzetn1B0AOLzIsKXIiVYem6lu0yH4hk0mYkwTvz9
lVpD80yATs5Qy1nkTE4IH5rWzPI3iDQzv2M8DDpoY9Krz0LNdD1N4X126yMCS7IeweLsEdVbHW4+PhGYNakqv1t7SjxbrzgNgM2Q
3Q5Wh1AoFHw5fS++hHTjnR68PdEuJ4ucQwY8/p28mcZO9coz33ws+p/1ISMCZt6LOYG9BaRaYJkS2nHsPd+tO5lwOOWr6Q="
    
jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  - mvn test -B -P coverage
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
